name: ${APP_NAME}_${NODE_ENV}
services:
  app:
    container_name: ${APP_NAME}.${NODE_ENV}
    image: ${APP_NAME}.${NODE_ENV}:latest
    build:
      target: ${NODE_ENV}
      context: .
      dockerfile: docker/Dockerfile.front
      args:
        - NODE_ENV=${NODE_ENV}
        - VITE_APP_PORT=${VITE_APP_PORT}
        - VITE_APP_DOMAIN=${VITE_APP_DOMAIN}
        - VITE_BFF_URL=${VITE_BFF_URL}
        - VITE_API_URL=${VITE_API_URL}
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_APP_PORT=${VITE_APP_PORT}
      - VITE_APP_DOMAIN=${VITE_APP_DOMAIN}
      - VITE_BFF_URL=${VITE_BFF_URL}
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${VITE_APP_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}.tls=true"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=myresolver"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${VITE_APP_PORT}"
  bff:
    container_name: ${APP_NAME}-bff.${NODE_ENV}
    image: ${APP_NAME}-bff.${NODE_ENV}:latest
    build:
      target: ${NODE_ENV}
      context: .
      dockerfile: docker/Dockerfile.bff
    environment:
      - NODE_ENV=${NODE_ENV}
      - BFF_PORT=${BFF_PORT}
      - APP_URL=${APP_URL}
      - VITE_API_URL=${VITE_API_URL}
      - API_TOKEN=${API_TOKEN}
    extra_hosts:
      - "${API_DOMAIN}:host-gateway"
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}-bff.rule=Host(`${BFF_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}-bff.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}-bff.tls.certresolver=myresolver"
      - "traefik.http.services.${APP_NAME}-bff.loadbalancer.server.port=${BFF_PORT}"

networks:
  traefik-net:
    external: true
