services:
  app:

    develop:
      watch:
        - action: sync
          path: ./core/front
          target: .
          ignore:
            - node_modules
            - dist
        - action: rebuild
          path: ./core/front/package.json
    ports:
      - "${VITE_APP_PORT}:${VITE_APP_PORT}"
    labels:
      - "traefik.http.routers.${APP_NAME}.tls=true"
  bff:

    develop:
      watch:
        - action: sync
          path: ./core/bff
          target: .
          ignore:
            - node_modules
        - action: rebuild
          path: ./core/bff/package.json
    ports:
      - "${BFF_PORT}:${BFF_PORT}"
    labels:
      - "traefik.http.routers.${APP_NAME}-bff.tls=true"
