#———————————————————————————————————————————#
# BASE                                      #
#———————————————————————————————————————————#
FROM node:24-alpine AS base

WORKDIR /app

COPY ./core/front/package*.json .
RUN npm install

COPY ./core/front .

EXPOSE ${APP_PORT}

#———————————————————————————————————————————#
# DEV                                       #
#———————————————————————————————————————————#
FROM base AS development

CMD ["npm", "run", "dev"]

#———————————————————————————————————————————#
# PROD                                      #
#———————————————————————————————————————————#
FROM base AS build
RUN npm run build

FROM nginx:stable-alpine AS production

COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

USER nginx

CMD ["nginx", "-g", "daemon off;"]