#———————————————————————————————————————————#
# BASE                                      #
#———————————————————————————————————————————#
FROM node:24-alpine AS base

WORKDIR /app

COPY ./core/front/package*.json .
RUN npm install

COPY ./core/front .

EXPOSE ${APP_PORT}

#———————————————————————————————————————————#
# DEV                                       #
#———————————————————————————————————————————#
FROM base AS development

CMD ["npm", "run", "dev"]

#———————————————————————————————————————————#
# PROD                                      #
#———————————————————————————————————————————#
FROM base AS build

ARG NODE_ENV
ARG VITE_API_URL
ARG VITE_BFF_URL
ARG VITE_APP_DOMAIN

ENV NODE_ENV=${NODE_ENV}
ENV VITE_API_URL=${VITE_API_URL}
ENV VITE_BFF_URL=${VITE_BFF_URL}
ENV VITE_APP_DOMAIN=${VITE_APP_DOMAIN}

RUN npm run build

FROM nginx:stable-alpine AS production

COPY ./docker/nginx/default.conf /etc/nginx/templates/default.conf.template
COPY --from=build /app/dist /usr/share/nginx/html

RUN touch /var/run/nginx.pid && \
    sed -i '/user  nginx;/d' /etc/nginx/nginx.conf && \
    chown -R nginx:nginx /var/run/nginx.pid /etc/nginx /var/cache/nginx /var/log/nginx

USER nginx

CMD ["nginx", "-g", "daemon off;"]