FROM node:24-alpine AS base

WORKDIR /app

COPY ./core/bff .
RUN npm install

EXPOSE ${BFF_PORT}

USER node

FROM base AS development
CMD ["npm", "run", "dev"]

FROM base AS production
CMD ["npm", "run", "start"]