services:
  app:
    develop:
      watch:
        - action: sync
          path: ./core/front
          target: /app
          ignore:
            - node_modules
            - dist
        - action: rebuild
          path: ./core/front/package.json
        - action: restart
          path: .env
    ports:
      - "${VITE_APP_PORT}:${VITE_APP_PORT}"
  bff:
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=${NODE_TLS_REJECT_UNAUTHORIZED}
    develop:
      watch:
        - action: sync
          path: ./core/bff
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: ./core/bff/package.json
        - action: restart
          path: .env
    ports:
      - "${BFF_PORT}:${BFF_PORT}"
